### ISSUE TITLE
Remove path from id in id_builder

### ISSUE THREAD

**Issue by hongkongkiwi** [magodo/terraform-provider-restful#105]
I would like to work with this Azure API: https://learn.microsoft.com/en-us/rest/api/speechtotext/web-hooks/create?view=rest-speechtotext-v3.2-preview.2&tabs=HTTP

Basically we make a post call to: https://westus.api.cognitive.microsoft.com/speechtotext/v3.2-preview.2/webhooks

When creating the object it returns an id key named "self".

However after the create call, the key needs a minor modification to remove the path we jsut called (NOT the base_url, but the actual path)
```
{
  "self": "https://westus.api.cognitive.microsoft.com/speechtotext/v3.2-preview.2/webhooks/2e856efe-ef53-465a-a632-6a084c1d349d",
}
```

The ID for subsequent delete calls is only 2e856efe-ef53-465a-a632-6a084c1d349d

There's an option #{body.self} which removes the base_url prefix.... but is there an option to remove the full path we just called (not only the base_url) ? 

I think this would resolve my issue.

**Comment by magodo** [comment]
@hongkongkiwi Can you try with the `main` branch to see if it fixes your issue. Then I'll do a new release.

In your case, if the `self` remains in the state file. Then you can do `delete_path = $url_path.trim_path(body.self)`.

**Comment by hongkongkiwi** [comment]
Just tested the latest change, works well!
