### ISSUE TITLE
Different HTTP path and method for update operation?

### ISSUE THREAD

**Issue by hongkongkiwi** [magodo/terraform-provider-restful#106]
Is there a way to set a different http method for Update operations?

I'm trying to use this API: https://learn.microsoft.com/en-us/rest/api/speechtotext/web-hooks?view=rest-speechtotext-v3.2

e.g. **POST** for create, **PATCH** for update ?

I guess I would also like to supply a different path for the update operation (as this includes the ID) e.g. /speechtotext/v3.2/webhooks/{id}

**Comment by magodo** [comment]
Does `update_method` and `update_path` work for you?

**Comment by hongkongkiwi** [comment]
Yup that works well thank you.

If possible, I think an `update_body` would also be a great addition.

In the case I linked above it's not needed, but there are some other APIs I'm looking at where there are a couple of fields which can only be set during creation and are not allowed to be modified after the initial create, so an` update_body` would allow to omit those fields on the update operation.

**Comment by magodo** [comment]
@hongkongkiwi The `body` is expected to be tracked in the state, whose latest state is retireved from the read. This is not possible for the `update_body`. So in your case, you probably just want a `restful_operation` to do the update as a one time effort right after the `restful_resource` is created, and set those fields as ignored in the `restful_resource` lifecycle annotation.

On the other hand, you can do a two steps apply, first apply to create the resource, then apply to update those properties via `PATCH` (which uses merge patch by default, that only includes the properties you are interested in).

**Comment by hongkongkiwi** [comment]
Makes sense, thank you.
