### ISSUE TITLE
New Versioned Release ?

### ISSUE THREAD

**Issue by hongkongkiwi** [magodo/terraform-provider-restful#114]
With the recent breaking changes, is it possible to release a new version? i'm using the local version for testing but it'd be great to have a new version release so I can switch back to the official version.

**Comment by magodo** [comment]
@hongkongkiwi I've just released the v0.16.1 (and v0.16.0), is that what you are looking for?

**Comment by hongkongkiwi** [comment]
Perfect! Thanks
