### ISSUE TITLE
Support locks

### ISSUE THREAD

**Issue by magodo** [magodo/terraform-provider-restful#32]
Add supports for locking resources that have no direct dependencies, but are conflicting to be modified at the same time.

**Comment by LaurentLesle** [comment]
@magodo Can it be addressed with #53 Refactor the precheck_* attribute to a block ?
Do you have an example?

**Comment by magodo** [comment]
@LaurentLesle Sounds good! Probably we shall introduce different types of checks, e.g. by `api`, by `mutex`, etc. I think it is also a benefit to allow finer grained lock for different operations rather than an opinionated lock used for all the operations.
