### ISSUE TITLE
Support for resource lifecycle for restful_operation

### ISSUE THREAD

**Issue by tmarshall98** [magodo/terraform-provider-restful#40]
Greetings,

I would like to request the addition of support for resource lifecycle controls for the restful_operation resource, I am specifically in need of [replace_triggered_by](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#replace_triggered_by).
To explain my use case:
I have a restful operation that is called Ansible AWX for provisioning VMs with Ansible.
With the current lack of lifecycle support, once the poll status job succeeds once, I have to taint/remove the restful_operation state in order to run the job again.
But it is common to want to rerun the create operation to spawn a new job, that will in turn apply new scripts to the VM.

Thank you in advance, if you need any additional information please let me know,

**Comment by magodo** [comment]
@tmarshall98 Thank you for reporting this! I believe as long as you are using Terraform >= v1.2.0, you can directly use the `replace_triggered_by` lifecycle argument. There is nothing need to be done at provider side.

E.g. I have following config:

```hcl
terraform {
  required_providers {
    restful = {
      source = "magodo/restful"
    }
  }
}

provider "restful" {
  base_url = "http://localhost:3000"
}

resource "restful_resource" "test" {
  path = "posts"
  body = jsonencode({
    type = "resource"
  })
  read_path = "$(path)/$(body.id)"
}

resource "restful_operation" "test" {
  method = "POST"
  path   = "opts"
  body = jsonencode({
    type = "op"
  })
  lifecycle {
    replace_triggered_by = [
      restful_resource.test
    ]
  }
}
```

After the first apply, if I update the `body` of the `restful_resource.test`, it will trigger a replace on the `restful_operation.test`, whose delete does nothing, and it's create will run the operation again. I assume this is what you are seeking for?

**Comment by tmarshall98** [comment]
@magodo thanks for the sample, 
I did try something similar and guess I did it wrong the first time. Glad this works out of the box.

Here is my sample where I set up the replace by to be triggered a by null resources, the null resource either changes when the body changes or if always_launch is true (by setting the trigger to the timestamp which is always different)

```
resource "null_resource" "always_launch" {
  triggers = {
    unique = var.always_launch ?  timestamp() : md5(local.body_json)
  }
}

resource "restful_operation" "launch_job" {
  path   = format("/api/v2/job_templates/%s/launch/", var.template_id)
  body   = local.body_json
  method = "POST"
  poll   = local.poll
  lifecycle {
    replace_triggered_by = [
      null_resource.always_launch
    ]
  }
}
```
