### ISSUE TITLE
data.restful_resource.output_attrs gjson filter is not working as expected on the returned attributes.

### ISSUE THREAD

**Issue by LaurentLesle** [magodo/terraform-provider-restful#68]
Scenario 1 - **The following example is working**

```hcl
data "restful_resource" "policy_definitions" {
  id = format("providers/Microsoft.Management/managementGroups/%s/providers/Microsoft.Authorization/policyDefinitions", var.root_id)
  query = {
    api-version = ["2021-06-01"]
    "$filter" = ["policyType eq 'Custom'"]
    "$top" = ["1"]
  }
  output_attrs = [
    "value"
  ]
}
```

returns as expected the value attribute:
![image](https://github.com/magodo/terraform-provider-restful/assets/4702224/fb01ab51-c0c5-4ebf-94f7-1683c3f3eaf6)

Scenario 2 - Want to retrieve only **id** and **name**

```hcl
data "restful_resource" "policy_definitions" {
  id = format("providers/Microsoft.Management/managementGroups/%s/providers/Microsoft.Authorization/policyDefinitions", var.root_id)
  query = {
    api-version = ["2021-06-01"]
    "$filter" = ["policyType eq 'Custom'"]
    "$top" = ["1"]
  }
  output_attrs = [
    "value.#.id",
    "value.#.name"
  ]
}
```

![image](https://github.com/magodo/terraform-provider-restful/assets/4702224/8cc6593b-c50f-4a2f-9bfe-7adde12d9a02)

The "jsondecode(data.restful_resource.policy_definitions.output)" does not return the expected structure of the object.

Expected result:

```hcl
Changes to Outputs:
  + policy_definitions = [
          + {
              + id         = "/providers/Microsoft.Management/managementGroups/xxxxx/providers/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-EventGridTopic"
              + name       = "Deploy-Diagnostics-EventGridTopic"
            }
          ]
```

**Comment by magodo** [comment]
@LaurentLesle Would you mind test your use case based on #70?

**Comment by LaurentLesle** [comment]
Yes I can confirm it is now working
![image](https://github.com/magodo/terraform-provider-restful/assets/4702224/2b45f707-a53b-4be1-b203-6de0535b75f5)
