### ISSUE TITLE
header.location is parsed by resource.restful_operation removing some important query strings in the location url

### ISSUE THREAD

**Issue by LaurentLesle** [magodo/terraform-provider-restful#69]
If a POST operation generates an async location containing query strings with api-version and other parameters, the provider removes those additional query strings and it results in an error when processing the async operation URL

![image](https://github.com/magodo/terraform-provider-restful/assets/4702224/44fd94c8-ce9d-43cf-842f-42962721162f)

Only api-version is kept, resulting into a 401 when the provider tries to read the async job

![image](https://github.com/magodo/terraform-provider-restful/assets/4702224/1ecd9c24-d5c2-40ae-b5d9-831d7166ffee)

**Comment by magodo** [comment]
@LaurentLesle Would you mind test this based on #73?

**Comment by LaurentLesle** [comment]
Yes I can confirm #73 is not following the header.location URL. 
![image](https://github.com/magodo/terraform-provider-restful/assets/4702224/685026a1-44df-41f4-a6f2-a68e30896e3c)
