### ISSUE TITLE
Cannot set success code to 422

### ISSUE THREAD

**Issue by ismailelmaarouf-loreal** [magodo/terraform-provider-restful#80]
Hello

I am trying to use this module to trigger API calls which may return 422 or 201, but I am only/mainly interested in creating the call via a Terraform resource. This seems to be impossible despite the fact that I set the return code to the correct 422 string. Is this expected behaviour? In which case what is the exact use of the "success" parameter?

Here is a snippet of what I am trying:

```
resource "restful_resource" "example" {

  path = "/mypath"
  create_method = "POST"

  body = jsonencode({
    email    = "myemail@domain.com"
  })

  poll_create = {
    status_locator = "code"
    status = {
      success = "422"
    }
  }
}
```

**Comment by magodo** [comment]
The `poll_create` is for polling the async operations (a.k.a long running operations) where the API returns 202 and kick of the job, then asks the users to poll the status of the job. So you probably don't need to use this property.

Alternatively, you might want to use [retry-create](https://registry.terraform.io/providers/magodo/restful/latest/docs/resources/resource#nested-schema-for-retry_create), whilst it will still regard 422 as a failure. As currently, the provider only regards 2xx as a successful operation.

BTW, when specifying for a `code`, use numbers isntead of strings.

**Comment by ismailelmaarouf-loreal** [comment]
Hi
Thanks for your reply. Yes I did try "retry" but the result was the same.
So I understand it is not possible to set the 'success' status code to something else than 2XX.
Thanks for your help.
