### ISSUE TITLE
How to solve mismatch between the PUT request body and GET response body

### ISSUE THREAD

**Issue by wilkejo** [magodo/terraform-provider-restful#89]
Hello,

I'd like to ask for guidance how to handle situations when the PUT request body does not match the GET response body - currently terraform fails with 

```txt
╷
│ Error: Modifying `body` during Read
│ 
│   with restful_resource.user_permissions,
│   on main.tf line 79, in resource "restful_resource" "user_permissions":
│   79: resource "restful_resource" "user_permissions" {
│ 
│ unmarshal the base "[{\"clusterId\":\"cold-sunset\",\"permissions\":[\"topicConsume\",\"topicViewConfig\"],\"resourceType\":\"Topic\",\"topicPattern\":\"abc_*\"}]": json: cannot unmarshal array into Go value of type map[string]interface {}
╵
```

What I tried so far
```hcl
resource "restful_resource" "user_permissions" {
  path          = "/public/v1/users/${local.user.email}/permissions"
  read_path     = "/public/v1/users/${local.user.email}/permissions"
  create_method = "PUT"
  update_method = "PATCH"

  body = jsonencode([{
    resourceType = "Topic",
    clusterId    = "cold-sunset",
    topicPattern = "abc_*",
    permissions = [
      "topicConsume",
      "topicViewConfig"
    ],
    }
  ])
  read_selector = "user.#(resourceType==\"Topic\")"
}
```

For `set permission` this is the PUT URL `/public/v1/users/{email}/permissions`

with the example payload from the API documentation

```json
[
  {
    "resourceType": "Topic",
    "clusterId": "my-cluster",
    "topicPattern": "finance-*",
    "permissions": [
      "topicCreate",
      "topicDelete"
    ]
  }
]
```
This is the GET URL `/public/v1/users/{email}/permissions` 

and the example response

```json
{
  "user": [
    {
      "resourceType": "Topic",
      "clusterId": "my-cluster",
      "topicPattern": "finance-*",
      "permissions": [
        "topicCreate",
        "topicDelete"
      ]
    }
  ],
  "groups": {
    "42": [
      {
        "resourceType": "Topic",
        "clusterId": "my-cluster",
        "topicPattern": "finance-*",
        "permissions": [
          "topicRead"
        ]
      }
    ]
  }
}
```

My understanding is that the provider sends an PUT request and verifies the repsonse using a get request. Therefore I added the read_select in (hopefully) valid gjson syntax to only us the user block.

The set permissions call only returns an empty body with status code 204.

Thank you for any feedback

**Comment by magodo** [comment]
@wilkejo Thank you for submitting this! There is no issue in your usage, but a bug in the provider.

**Comment by wilkejo** [comment]
Hello @magodo ,
thank you for the fast response and quick fix. 
Can you release this in the terraform provider repo (as 0.12.1) or how can I use the fixed version. Is there a possibility to load the latest main branch in the provider config?
Thank you

**Comment by wilkejo** [comment]
Got it working locally, not sure how to do it in a pipeline.

1. checked out the project
2. build it locally with `go build`
3. copied the build result to my .terraform/plugins folder 
4. run terraform init 

everything worked

**Comment by magodo** [comment]
@wilkejo v0.13.0 is released yesterday (right after I saw your message above :))
