### ISSUE TITLE
API Patch with Array - Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by wilkejo** [magodo/terraform-provider-restful#91]
Hello,

after the latest release - thank you! - I encountered the next issue with my API which uses arrays.

I first create a set of permissions like this 
```hcl
resource "restful_resource" "user_permissions" {
  path            = "/public/v1/users/${local.user.email}/permissions"
  read_path       = "/public/v1/users/${local.user.email}/permissions"
  create_method   = "PUT"
  update_method   = "PATCH"

  merge_patch_disabled = true

  body = jsonencode([
    {
      resourceType = "Topic",
      clusterId    = "cold-sunset",
      topicPattern = "wcr_*",
      permissions = [
        "topicConsume",
        "topicViewConfig"
      ],
    },
    {
      resourceType = "Topic",
      clusterId    = "test-sasl",
      topicPattern = "wcr_*",
      permissions  = [
        "topicConsume",
        "topicViewConfig"
      ],
    }
  ])
  read_selector = "user"
}
```
The apply and everything else works fine.

Now I extend the list and the plan works fine

```hcl
resource "restful_resource" "user_permissions" {
  path            = "/public/v1/users/${local.user.email}/permissions"
  read_path       = "/public/v1/users/${local.user.email}/permissions"
  create_method   = "PUT"
  update_method   = "PATCH"
  check_existance = false

  merge_patch_disabled = true

  body = jsonencode([
    {
      resourceType = "Topic",
      clusterId    = "cold-sunset",
      topicPattern = "wcr_*",
      permissions = [
        "topicConsume",
        "topicViewConfig"
      ],
    },
    {
      resourceType = "Topic",
      clusterId    = "test-sasl-akhq",
      topicPattern = "wcr_*",
      permissions  = [
        "topicConsume",
        "topicViewConfig"
      ],
    },
    {
      resourceType = "Topic",
      clusterId    = "release-preprod",
      topicPattern = "wcr_*",
      permissions = [
        "topicConsume",
        "topicViewConfig"
      ],
    }
  ])
  read_selector = "user"

  lifecycle {

  }
}
```

The apply results in the following error

```txt
│ Error: Provider produced inconsistent result after apply │  
│ When applying changes to restful_resource.user_permissions, provider "provider[\"registry.terraform.io/magodo/restful\"]" produced an unexpected new value: .body: was │ cty.StringVal("[{\"clusterId\":\"cold-sunset\",\"permissions\":[\"topicConsume\",\"topicViewConfig\"],\"resourceType\":\"Topic\",\"topicPattern\":\"wcr_*\"},{\"clusterId\":\"test-sasl\",\"permissions\":[\"topicConsume\",\"topicViewConfig\"],\"resourceType\":\"Topic\",\"topicPattern\":\"wcr_*\"}]"), │ 
but now 
│ cty.StringVal("[{\"clusterId\":\"release-preprod\",\"permissions\":[\"topicConsume\",\"topicViewConfig\"],\"resourceType\":\"Topic\",\"topicPattern\":\"wcr_*\"},{\"clusterId\":\"cold-sunset\",\"permissions\":[\"topicConsume\",\"topicViewConfig\"],\"resourceType\":\"Topic\",\"topicPattern\":\"wcr_*\"},{\"clusterId\":\"test-sasl\",\"permissions\":[\"topicConsume\",\"topicViewConfig\"],\"resourceType\":\"Topic\",\"topicPattern\":\"wcr_*\"}]"). │  
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

The strings are the same but the order is different. I saw this very often, that terraform sorts from Z to A where others sort from A to Z.

I had a look into the source code but couldn't find the location where this maybe could change. Any hints and I could try to create a MR.

**Comment by wilkejo** [comment]
I did further research and when I changed the order in terraform to the expected result it worked. So it depends what the API returns and how terraform lools like. 

Probably you need to sort the feedback from the API and the terraform configuration so ensure they match. Don't know if this is a feasable approach.

**Comment by magodo** [comment]
@wilkejo Thank you for reaching out! This is exactly what the upcoming [dynamic type](https://github.com/magodo/terraform-provider-restful/issues/83) gonna solve.

Would you mind try to build the provider with the `dynamic` branch and test it out? The breaking changes are listed at https://github.com/magodo/terraform-provider-restful/pull/87.

**Comment by wilkejo** [comment]
I build a version from the dynamic branch. 

I got the following error. 

```txt
╷
│ Error: Unable to Read Previously Saved State for UpgradeResourceState
│ 
│   with restful_resource.user,
│   on main.tf line 26, in resource "restful_resource" "user":
│   26: resource "restful_resource" "user" {
│ 
│ There was an error reading the saved resource state using the current resource schema.
│ 
│ If this resource state was last refreshed with Terraform CLI 0.11 and earlier, it must be refreshed or applied with an older provider version first. If you manually modified the resource state, you will need to manually modify it to match the current resource
│ schema. Otherwise, please report this to the provider developer:
│ 
│ AttributeName("body"): invalid JSON, expected "{", got "{\"email\":\"a.b@c.com\",\"firstName\":\"a\",\"lastName\":\"b\"}"
╵
```
I deleted the resource from my statefile and re-created it. This worked well.
I compared the resources in the statefile and (as expected) the look different b/c it is not an encoded JSON anymore.

I have a good feeling on your new development / dynamic branch but didn't find a way how I would do a migration of the resources in the statefile without deleting the resources.

I also tried to import a resource but didn't know how an import should look like.

**Comment by wilkejo** [comment]
I tested further and the inconsistent issue seems to be fixed by the dynamic version.

There is (maybe) an other issue if the body includes a list of values. I have two different APIs and I tested with 0.13.0 and the dynamic version

### with 0.13.0

the body looks like this

```hcl
  body = jsonencode({
    name     = "Some Name"
    creator  = "<mail-address>"
    teamMail = "<mail-address>",
    members  = [
      userF,
      userA,
      userD,
      userB
    ]
  })
```

I can apply the resources and also do a plan. Every terraform run wants to update the resource in place, as the order of the users  is returned from the API in a different or no order 

### with dynamic provider

different API 
the body looks like
```hcl
body =  [
            {
                clusterId    = "a"
                permissions  = [
                    "topicConsume",
                    "topicViewConfig",
                ]
                resourceType = "Topic"
                topicPattern = "wcr_*"
            },
            {
                clusterId    = "b"
                permissions  = [
                    "topicConsume",
                    "topicViewConfig",
                ]
                resourceType = "Topic"
                topicPattern = "wcr_*"
            },
...
           
]
```
same behaviour as in 0.13.0 terraform plans to update the resources in place.

--
It could be possible to check the state body, the plan body and the response body if an array is in the response and sort it. If arrays in the body are sorted maybe the changes will not be shown?

**Comment by magodo** [comment]
@wilkejo Thank you for testing this out!

For the order issue, as is mentioned in https://github.com/magodo/terraform-provider-restful/issues/83, you can use `toset` function to decorate the list that you want to ignore order.

For the migration issue, I plan to implement a state migration for it once I have the bandwidth. That's the reason why this branch is still not merged and released :)

**Comment by wilkejo** [comment]
@magodo it tried it with the new dynamic version and first stumpled on the issue that my body is a type `tuple` with different elements. A conversion to set was not possible. error message: `cannot convert tuple to set of any single type.`

I removed objects from the list to have a list with similar objects and `toset` worked. 

This sort issue was not solved. I conclude that toset is not sorting a list of objects. How could it sort them. It had to select one value of the object which would be the sort key.

**Comment by magodo** [comment]
@wilkejo `toset` doesn't sort the object at all, it ignores the order, which means the followings are the same:

- `toset([{"name": "foo"}, {"name": "bar"}])`
- `toset([{"name": "bar"}, {"name": "foo"}])`

Presumably, you'll first need a *dummy* `apply` to allow `terraform` to update your state file, to reflect the type change from `tuple` to `set of objects`. Then things should be work going forwards.

**Comment by magodo** [comment]
@wilkejo I've made a new commit in the `dynamic` branch, which adds support of the state migration now. FYI.

**Comment by magodo** [comment]
@wilkejo The expected "from" state is of `schema_version` equals to 0 and `body` be of string type, e.g.

```
    {
      "mode": "managed",
      "type": "restful_resource",
      "name": "test",
      "provider": "provider[\"registry.terraform.io/magodo/restful\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "body": "{\"abc\":[{\"name\":\"foo\"},{\"name\":\"bar\"}],\"foo\":\"bar2\"}",
            "check_existance": null,
            "create_method": null,
```

With this, when upgrading the provider to the `dynamic` branch, it will migrate above into following:

```
      "provider": "provider[\"registry.terraform.io/magodo/restful\"]",
      "instances": [
        {
          "schema_version": 1,
          "attributes": {
            "body": {
              "value": {
                "abc": [
                  {
                    "name": "foo"
                  },
                  {
                    "name": "bar"
                  }
                ],
                "foo": "bar2"
              },
              "type": [
                "object",
                {
                  "abc": [
                    "tuple",
                    [
                      [
                        "object",
                        {
                          "name": "string"
                        }
                      ],
                      [
                        "object",
                        {
                          "name": "string"
                        }
                      ]
                    ]
                  ],
                  "foo": "string"
                }
              ]
            },
            "check_existance": null,
            "create_method": null,
```

I'm not sure how you have `schema_version` equals to 0 and `body` is not a string..

**Comment by wilkejo** [comment]
Ok, this was probably bad explenation from my site.
The statefile was written with version 1 (provider from the dynamic branch). I understand it is looking for version 0.
I think that answered my question. 

Also I checked again and your comment regarding the set looks also fine.
