### ISSUE TITLE
restful_resource - unmarshal the body "": unexpected end of JSON input

### ISSUE THREAD

**Issue by theadzik** [magodo/terraform-provider-restful#92]
Hi,

I'm using `restful_resource` from 0.13.0 provider version to create shared Azure DevOps service endpoints: https://learn.microsoft.com/en-us/rest/api/azure/devops/serviceendpoint/endpoints/share-service-endpoint?view=azure-devops-rest-7.0&tabs=HTTP

It creates, deletes and updates connections correctly. When the shared endpoint is deleted outside of terraform I get an error when reading the object:

```text
Planning failed. Terraform encountered an error while generating this plan.

│ Error: Modifying `body` during Read
...
│ unmarshal the body "": unexpected end of JSON input
```

When reading (GET), the API returns 200 with null body if the resource doesn't exist. I expect this error is because I'm using read_selector? How can I make the `restful_resource` treat null reposnes with 200 code as "this object doesn't exist"?

Below is my (anonymized and simplfied) code.

```hcl
resource "restful_resource" "project_share" {
  read_path     = "/my-org/my-project/_apis/serviceendpoint/endpoints/${azuredevops_serviceendpoint_kubernetes.this.id}?api-version=7.0}"
  read_selector = "serviceEndpointProjectReferences.#(projectReference.name==\"my-project\")#"
  create_method = "PATCH"
  create_selector = "serviceEndpointProjectReferences.#(projectReference.name==\"my-project\")#"
  path          = "/my-org/_apis/serviceendpoint/endpoints/${azuredevops_serviceendpoint_kubernetes.this.id}?api-version=7.0"
  body          = jsonencode(
    [
      {
        name : azuredevops_serviceendpoint_kubernetes.this.service_endpoint_name,
        projectReference : {
          id : "1234-1234-1234",
          name : "my-project"
        },
        description : "Managed by Terraform"
      }
    ]
  )

  delete_method = "DELETE"
  delete_path   = "/my-org/_apis/serviceendpoint/endpoints/${azuredevops_serviceendpoint_kubernetes.this.id}?projectIds=1234-1234-1234&api-version=7.0"
}
```

**Comment by wilkejo** [comment]
Did you try the poll delete option? Within the examples I saw this one related to azure.
https://github.com/magodo/terraform-provider-restful/blob/main/examples/usecases/azure/virtual_network/main.tf#L45

**Comment by theadzik** [comment]
> Did you try the poll delete option? Within the examples I saw this one related to azure. https://github.com/magodo/terraform-provider-restful/blob/main/examples/usecases/azure/virtual_network/main.tf#L45

I haven't but I'm not deleting anything. I might misunderstood what "poll_xxx" does, but I think it only kicks in when deleting the object from inside terraform?

Unless I do something like

```hcl
poll_delete = {
    status_locator = "body"
    status = {
      success = ""
    }
  }
```
??

I tried 

```hcl
  retry_read = {
    status = {
      success = "200"
    }
    status_locator = "code"
  }
```

but it did nothing

**Comment by wilkejo** [comment]
Ok. Now I remember you wrote it was deleted outsite of terraform. Than I don't know
