### ISSUE TITLE
tls_insecure_skip_verify is not expected as an attribute

### ISSUE THREAD

**Issue by vTrex-BC** [magodo/terraform-provider-restful#93]
With the new version 0.13.0 the tls_insecure_skip_verify is not recognized as an attribute anymore.
Workaround was to downgrade to 0.12.0 where it is still working.

**Comment by wilkejo** [comment]
Hello,
just to verify. Did you see that the configuration was moved?

https://github.com/magodo/terraform-provider-restful/pull/82
https://registry.terraform.io/providers/magodo/restful/latest/docs#tls_insecure_skip_verify

**Comment by magodo** [comment]
@vTrex-BC Sorry that this breaking change affects your existing workflows. As @wilkejo just mentioned, the `tls_insecure_skip_verify` (and `cookie_enabled`) are moved from top-level under `client` in v0.13.0. So would you please change your provider config if you intend to upgrade the version?

**Comment by lkwg82** [comment]
this works, can be closed
